# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b815322566e2d594c1b583ce46117ad78f4577c852bff09f0a5d4474ee9ae5b2ca5b5af52ee088168d396a23bf5a998cf85f0c55018bd5ebfa4841e29146823b

test:
  secret_key_base: d36bf6377bc4b539ba4e0dfbeacb3550d5a4dff50a4288095e76cb94e710a1bdfa250a391e06a2ed03f31f68dc4ad959a05f8a7ab30f271f11f5511e09532d54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
